process.on('uncaughtException', (err: any) => {
  console.error(err);
});

